# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ksoo/QCProgram

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ksoo/QCProgram

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ksoo/QCProgram/CMakeFiles /home/ksoo/QCProgram/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ksoo/QCProgram/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named FOO-0.1.out

# Build rule for target.
FOO-0.1.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FOO-0.1.out
.PHONY : FOO-0.1.out

# fast build rule for target.
FOO-0.1.out/fast:
	$(MAKE) -f CMakeFiles/FOO-0.1.out.dir/build.make CMakeFiles/FOO-0.1.out.dir/build
.PHONY : FOO-0.1.out/fast

JuceLibraryCode/include_juce_audio_basics.o: JuceLibraryCode/include_juce_audio_basics.cpp.o

.PHONY : JuceLibraryCode/include_juce_audio_basics.o

# target to build an object file
JuceLibraryCode/include_juce_audio_basics.cpp.o:
	$(MAKE) -f CMakeFiles/FOO-0.1.out.dir/build.make CMakeFiles/FOO-0.1.out.dir/JuceLibraryCode/include_juce_audio_basics.cpp.o
.PHONY : JuceLibraryCode/include_juce_audio_basics.cpp.o

JuceLibraryCode/include_juce_audio_basics.i: JuceLibraryCode/include_juce_audio_basics.cpp.i

.PHONY : JuceLibraryCode/include_juce_audio_basics.i

# target to preprocess a source file
JuceLibraryCode/include_juce_audio_basics.cpp.i:
	$(MAKE) -f CMakeFiles/FOO-0.1.out.dir/build.make CMakeFiles/FOO-0.1.out.dir/JuceLibraryCode/include_juce_audio_basics.cpp.i
.PHONY : JuceLibraryCode/include_juce_audio_basics.cpp.i

JuceLibraryCode/include_juce_audio_basics.s: JuceLibraryCode/include_juce_audio_basics.cpp.s

.PHONY : JuceLibraryCode/include_juce_audio_basics.s

# target to generate assembly for a file
JuceLibraryCode/include_juce_audio_basics.cpp.s:
	$(MAKE) -f CMakeFiles/FOO-0.1.out.dir/build.make CMakeFiles/FOO-0.1.out.dir/JuceLibraryCode/include_juce_audio_basics.cpp.s
.PHONY : JuceLibraryCode/include_juce_audio_basics.cpp.s

JuceLibraryCode/include_juce_audio_devices.o: JuceLibraryCode/include_juce_audio_devices.cpp.o

.PHONY : JuceLibraryCode/include_juce_audio_devices.o

# target to build an object file
JuceLibraryCode/include_juce_audio_devices.cpp.o:
	$(MAKE) -f CMakeFiles/FOO-0.1.out.dir/build.make CMakeFiles/FOO-0.1.out.dir/JuceLibraryCode/include_juce_audio_devices.cpp.o
.PHONY : JuceLibraryCode/include_juce_audio_devices.cpp.o

JuceLibraryCode/include_juce_audio_devices.i: JuceLibraryCode/include_juce_audio_devices.cpp.i

.PHONY : JuceLibraryCode/include_juce_audio_devices.i

# target to preprocess a source file
JuceLibraryCode/include_juce_audio_devices.cpp.i:
	$(MAKE) -f CMakeFiles/FOO-0.1.out.dir/build.make CMakeFiles/FOO-0.1.out.dir/JuceLibraryCode/include_juce_audio_devices.cpp.i
.PHONY : JuceLibraryCode/include_juce_audio_devices.cpp.i

JuceLibraryCode/include_juce_audio_devices.s: JuceLibraryCode/include_juce_audio_devices.cpp.s

.PHONY : JuceLibraryCode/include_juce_audio_devices.s

# target to generate assembly for a file
JuceLibraryCode/include_juce_audio_devices.cpp.s:
	$(MAKE) -f CMakeFiles/FOO-0.1.out.dir/build.make CMakeFiles/FOO-0.1.out.dir/JuceLibraryCode/include_juce_audio_devices.cpp.s
.PHONY : JuceLibraryCode/include_juce_audio_devices.cpp.s

JuceLibraryCode/include_juce_audio_formats.o: JuceLibraryCode/include_juce_audio_formats.cpp.o

.PHONY : JuceLibraryCode/include_juce_audio_formats.o

# target to build an object file
JuceLibraryCode/include_juce_audio_formats.cpp.o:
	$(MAKE) -f CMakeFiles/FOO-0.1.out.dir/build.make CMakeFiles/FOO-0.1.out.dir/JuceLibraryCode/include_juce_audio_formats.cpp.o
.PHONY : JuceLibraryCode/include_juce_audio_formats.cpp.o

JuceLibraryCode/include_juce_audio_formats.i: JuceLibraryCode/include_juce_audio_formats.cpp.i

.PHONY : JuceLibraryCode/include_juce_audio_formats.i

# target to preprocess a source file
JuceLibraryCode/include_juce_audio_formats.cpp.i:
	$(MAKE) -f CMakeFiles/FOO-0.1.out.dir/build.make CMakeFiles/FOO-0.1.out.dir/JuceLibraryCode/include_juce_audio_formats.cpp.i
.PHONY : JuceLibraryCode/include_juce_audio_formats.cpp.i

JuceLibraryCode/include_juce_audio_formats.s: JuceLibraryCode/include_juce_audio_formats.cpp.s

.PHONY : JuceLibraryCode/include_juce_audio_formats.s

# target to generate assembly for a file
JuceLibraryCode/include_juce_audio_formats.cpp.s:
	$(MAKE) -f CMakeFiles/FOO-0.1.out.dir/build.make CMakeFiles/FOO-0.1.out.dir/JuceLibraryCode/include_juce_audio_formats.cpp.s
.PHONY : JuceLibraryCode/include_juce_audio_formats.cpp.s

JuceLibraryCode/include_juce_audio_processors.o: JuceLibraryCode/include_juce_audio_processors.cpp.o

.PHONY : JuceLibraryCode/include_juce_audio_processors.o

# target to build an object file
JuceLibraryCode/include_juce_audio_processors.cpp.o:
	$(MAKE) -f CMakeFiles/FOO-0.1.out.dir/build.make CMakeFiles/FOO-0.1.out.dir/JuceLibraryCode/include_juce_audio_processors.cpp.o
.PHONY : JuceLibraryCode/include_juce_audio_processors.cpp.o

JuceLibraryCode/include_juce_audio_processors.i: JuceLibraryCode/include_juce_audio_processors.cpp.i

.PHONY : JuceLibraryCode/include_juce_audio_processors.i

# target to preprocess a source file
JuceLibraryCode/include_juce_audio_processors.cpp.i:
	$(MAKE) -f CMakeFiles/FOO-0.1.out.dir/build.make CMakeFiles/FOO-0.1.out.dir/JuceLibraryCode/include_juce_audio_processors.cpp.i
.PHONY : JuceLibraryCode/include_juce_audio_processors.cpp.i

JuceLibraryCode/include_juce_audio_processors.s: JuceLibraryCode/include_juce_audio_processors.cpp.s

.PHONY : JuceLibraryCode/include_juce_audio_processors.s

# target to generate assembly for a file
JuceLibraryCode/include_juce_audio_processors.cpp.s:
	$(MAKE) -f CMakeFiles/FOO-0.1.out.dir/build.make CMakeFiles/FOO-0.1.out.dir/JuceLibraryCode/include_juce_audio_processors.cpp.s
.PHONY : JuceLibraryCode/include_juce_audio_processors.cpp.s

JuceLibraryCode/include_juce_core.o: JuceLibraryCode/include_juce_core.cpp.o

.PHONY : JuceLibraryCode/include_juce_core.o

# target to build an object file
JuceLibraryCode/include_juce_core.cpp.o:
	$(MAKE) -f CMakeFiles/FOO-0.1.out.dir/build.make CMakeFiles/FOO-0.1.out.dir/JuceLibraryCode/include_juce_core.cpp.o
.PHONY : JuceLibraryCode/include_juce_core.cpp.o

JuceLibraryCode/include_juce_core.i: JuceLibraryCode/include_juce_core.cpp.i

.PHONY : JuceLibraryCode/include_juce_core.i

# target to preprocess a source file
JuceLibraryCode/include_juce_core.cpp.i:
	$(MAKE) -f CMakeFiles/FOO-0.1.out.dir/build.make CMakeFiles/FOO-0.1.out.dir/JuceLibraryCode/include_juce_core.cpp.i
.PHONY : JuceLibraryCode/include_juce_core.cpp.i

JuceLibraryCode/include_juce_core.s: JuceLibraryCode/include_juce_core.cpp.s

.PHONY : JuceLibraryCode/include_juce_core.s

# target to generate assembly for a file
JuceLibraryCode/include_juce_core.cpp.s:
	$(MAKE) -f CMakeFiles/FOO-0.1.out.dir/build.make CMakeFiles/FOO-0.1.out.dir/JuceLibraryCode/include_juce_core.cpp.s
.PHONY : JuceLibraryCode/include_juce_core.cpp.s

JuceLibraryCode/include_juce_cryptography.o: JuceLibraryCode/include_juce_cryptography.cpp.o

.PHONY : JuceLibraryCode/include_juce_cryptography.o

# target to build an object file
JuceLibraryCode/include_juce_cryptography.cpp.o:
	$(MAKE) -f CMakeFiles/FOO-0.1.out.dir/build.make CMakeFiles/FOO-0.1.out.dir/JuceLibraryCode/include_juce_cryptography.cpp.o
.PHONY : JuceLibraryCode/include_juce_cryptography.cpp.o

JuceLibraryCode/include_juce_cryptography.i: JuceLibraryCode/include_juce_cryptography.cpp.i

.PHONY : JuceLibraryCode/include_juce_cryptography.i

# target to preprocess a source file
JuceLibraryCode/include_juce_cryptography.cpp.i:
	$(MAKE) -f CMakeFiles/FOO-0.1.out.dir/build.make CMakeFiles/FOO-0.1.out.dir/JuceLibraryCode/include_juce_cryptography.cpp.i
.PHONY : JuceLibraryCode/include_juce_cryptography.cpp.i

JuceLibraryCode/include_juce_cryptography.s: JuceLibraryCode/include_juce_cryptography.cpp.s

.PHONY : JuceLibraryCode/include_juce_cryptography.s

# target to generate assembly for a file
JuceLibraryCode/include_juce_cryptography.cpp.s:
	$(MAKE) -f CMakeFiles/FOO-0.1.out.dir/build.make CMakeFiles/FOO-0.1.out.dir/JuceLibraryCode/include_juce_cryptography.cpp.s
.PHONY : JuceLibraryCode/include_juce_cryptography.cpp.s

JuceLibraryCode/include_juce_data_structures.o: JuceLibraryCode/include_juce_data_structures.cpp.o

.PHONY : JuceLibraryCode/include_juce_data_structures.o

# target to build an object file
JuceLibraryCode/include_juce_data_structures.cpp.o:
	$(MAKE) -f CMakeFiles/FOO-0.1.out.dir/build.make CMakeFiles/FOO-0.1.out.dir/JuceLibraryCode/include_juce_data_structures.cpp.o
.PHONY : JuceLibraryCode/include_juce_data_structures.cpp.o

JuceLibraryCode/include_juce_data_structures.i: JuceLibraryCode/include_juce_data_structures.cpp.i

.PHONY : JuceLibraryCode/include_juce_data_structures.i

# target to preprocess a source file
JuceLibraryCode/include_juce_data_structures.cpp.i:
	$(MAKE) -f CMakeFiles/FOO-0.1.out.dir/build.make CMakeFiles/FOO-0.1.out.dir/JuceLibraryCode/include_juce_data_structures.cpp.i
.PHONY : JuceLibraryCode/include_juce_data_structures.cpp.i

JuceLibraryCode/include_juce_data_structures.s: JuceLibraryCode/include_juce_data_structures.cpp.s

.PHONY : JuceLibraryCode/include_juce_data_structures.s

# target to generate assembly for a file
JuceLibraryCode/include_juce_data_structures.cpp.s:
	$(MAKE) -f CMakeFiles/FOO-0.1.out.dir/build.make CMakeFiles/FOO-0.1.out.dir/JuceLibraryCode/include_juce_data_structures.cpp.s
.PHONY : JuceLibraryCode/include_juce_data_structures.cpp.s

JuceLibraryCode/include_juce_events.o: JuceLibraryCode/include_juce_events.cpp.o

.PHONY : JuceLibraryCode/include_juce_events.o

# target to build an object file
JuceLibraryCode/include_juce_events.cpp.o:
	$(MAKE) -f CMakeFiles/FOO-0.1.out.dir/build.make CMakeFiles/FOO-0.1.out.dir/JuceLibraryCode/include_juce_events.cpp.o
.PHONY : JuceLibraryCode/include_juce_events.cpp.o

JuceLibraryCode/include_juce_events.i: JuceLibraryCode/include_juce_events.cpp.i

.PHONY : JuceLibraryCode/include_juce_events.i

# target to preprocess a source file
JuceLibraryCode/include_juce_events.cpp.i:
	$(MAKE) -f CMakeFiles/FOO-0.1.out.dir/build.make CMakeFiles/FOO-0.1.out.dir/JuceLibraryCode/include_juce_events.cpp.i
.PHONY : JuceLibraryCode/include_juce_events.cpp.i

JuceLibraryCode/include_juce_events.s: JuceLibraryCode/include_juce_events.cpp.s

.PHONY : JuceLibraryCode/include_juce_events.s

# target to generate assembly for a file
JuceLibraryCode/include_juce_events.cpp.s:
	$(MAKE) -f CMakeFiles/FOO-0.1.out.dir/build.make CMakeFiles/FOO-0.1.out.dir/JuceLibraryCode/include_juce_events.cpp.s
.PHONY : JuceLibraryCode/include_juce_events.cpp.s

JuceLibraryCode/include_juce_graphics.o: JuceLibraryCode/include_juce_graphics.cpp.o

.PHONY : JuceLibraryCode/include_juce_graphics.o

# target to build an object file
JuceLibraryCode/include_juce_graphics.cpp.o:
	$(MAKE) -f CMakeFiles/FOO-0.1.out.dir/build.make CMakeFiles/FOO-0.1.out.dir/JuceLibraryCode/include_juce_graphics.cpp.o
.PHONY : JuceLibraryCode/include_juce_graphics.cpp.o

JuceLibraryCode/include_juce_graphics.i: JuceLibraryCode/include_juce_graphics.cpp.i

.PHONY : JuceLibraryCode/include_juce_graphics.i

# target to preprocess a source file
JuceLibraryCode/include_juce_graphics.cpp.i:
	$(MAKE) -f CMakeFiles/FOO-0.1.out.dir/build.make CMakeFiles/FOO-0.1.out.dir/JuceLibraryCode/include_juce_graphics.cpp.i
.PHONY : JuceLibraryCode/include_juce_graphics.cpp.i

JuceLibraryCode/include_juce_graphics.s: JuceLibraryCode/include_juce_graphics.cpp.s

.PHONY : JuceLibraryCode/include_juce_graphics.s

# target to generate assembly for a file
JuceLibraryCode/include_juce_graphics.cpp.s:
	$(MAKE) -f CMakeFiles/FOO-0.1.out.dir/build.make CMakeFiles/FOO-0.1.out.dir/JuceLibraryCode/include_juce_graphics.cpp.s
.PHONY : JuceLibraryCode/include_juce_graphics.cpp.s

JuceLibraryCode/include_juce_gui_basics.o: JuceLibraryCode/include_juce_gui_basics.cpp.o

.PHONY : JuceLibraryCode/include_juce_gui_basics.o

# target to build an object file
JuceLibraryCode/include_juce_gui_basics.cpp.o:
	$(MAKE) -f CMakeFiles/FOO-0.1.out.dir/build.make CMakeFiles/FOO-0.1.out.dir/JuceLibraryCode/include_juce_gui_basics.cpp.o
.PHONY : JuceLibraryCode/include_juce_gui_basics.cpp.o

JuceLibraryCode/include_juce_gui_basics.i: JuceLibraryCode/include_juce_gui_basics.cpp.i

.PHONY : JuceLibraryCode/include_juce_gui_basics.i

# target to preprocess a source file
JuceLibraryCode/include_juce_gui_basics.cpp.i:
	$(MAKE) -f CMakeFiles/FOO-0.1.out.dir/build.make CMakeFiles/FOO-0.1.out.dir/JuceLibraryCode/include_juce_gui_basics.cpp.i
.PHONY : JuceLibraryCode/include_juce_gui_basics.cpp.i

JuceLibraryCode/include_juce_gui_basics.s: JuceLibraryCode/include_juce_gui_basics.cpp.s

.PHONY : JuceLibraryCode/include_juce_gui_basics.s

# target to generate assembly for a file
JuceLibraryCode/include_juce_gui_basics.cpp.s:
	$(MAKE) -f CMakeFiles/FOO-0.1.out.dir/build.make CMakeFiles/FOO-0.1.out.dir/JuceLibraryCode/include_juce_gui_basics.cpp.s
.PHONY : JuceLibraryCode/include_juce_gui_basics.cpp.s

JuceLibraryCode/include_juce_gui_extra.o: JuceLibraryCode/include_juce_gui_extra.cpp.o

.PHONY : JuceLibraryCode/include_juce_gui_extra.o

# target to build an object file
JuceLibraryCode/include_juce_gui_extra.cpp.o:
	$(MAKE) -f CMakeFiles/FOO-0.1.out.dir/build.make CMakeFiles/FOO-0.1.out.dir/JuceLibraryCode/include_juce_gui_extra.cpp.o
.PHONY : JuceLibraryCode/include_juce_gui_extra.cpp.o

JuceLibraryCode/include_juce_gui_extra.i: JuceLibraryCode/include_juce_gui_extra.cpp.i

.PHONY : JuceLibraryCode/include_juce_gui_extra.i

# target to preprocess a source file
JuceLibraryCode/include_juce_gui_extra.cpp.i:
	$(MAKE) -f CMakeFiles/FOO-0.1.out.dir/build.make CMakeFiles/FOO-0.1.out.dir/JuceLibraryCode/include_juce_gui_extra.cpp.i
.PHONY : JuceLibraryCode/include_juce_gui_extra.cpp.i

JuceLibraryCode/include_juce_gui_extra.s: JuceLibraryCode/include_juce_gui_extra.cpp.s

.PHONY : JuceLibraryCode/include_juce_gui_extra.s

# target to generate assembly for a file
JuceLibraryCode/include_juce_gui_extra.cpp.s:
	$(MAKE) -f CMakeFiles/FOO-0.1.out.dir/build.make CMakeFiles/FOO-0.1.out.dir/JuceLibraryCode/include_juce_gui_extra.cpp.s
.PHONY : JuceLibraryCode/include_juce_gui_extra.cpp.s

JuceLibraryCode/include_juce_opengl.o: JuceLibraryCode/include_juce_opengl.cpp.o

.PHONY : JuceLibraryCode/include_juce_opengl.o

# target to build an object file
JuceLibraryCode/include_juce_opengl.cpp.o:
	$(MAKE) -f CMakeFiles/FOO-0.1.out.dir/build.make CMakeFiles/FOO-0.1.out.dir/JuceLibraryCode/include_juce_opengl.cpp.o
.PHONY : JuceLibraryCode/include_juce_opengl.cpp.o

JuceLibraryCode/include_juce_opengl.i: JuceLibraryCode/include_juce_opengl.cpp.i

.PHONY : JuceLibraryCode/include_juce_opengl.i

# target to preprocess a source file
JuceLibraryCode/include_juce_opengl.cpp.i:
	$(MAKE) -f CMakeFiles/FOO-0.1.out.dir/build.make CMakeFiles/FOO-0.1.out.dir/JuceLibraryCode/include_juce_opengl.cpp.i
.PHONY : JuceLibraryCode/include_juce_opengl.cpp.i

JuceLibraryCode/include_juce_opengl.s: JuceLibraryCode/include_juce_opengl.cpp.s

.PHONY : JuceLibraryCode/include_juce_opengl.s

# target to generate assembly for a file
JuceLibraryCode/include_juce_opengl.cpp.s:
	$(MAKE) -f CMakeFiles/FOO-0.1.out.dir/build.make CMakeFiles/FOO-0.1.out.dir/JuceLibraryCode/include_juce_opengl.cpp.s
.PHONY : JuceLibraryCode/include_juce_opengl.cpp.s

JuceLibraryCode/include_juce_video.o: JuceLibraryCode/include_juce_video.cpp.o

.PHONY : JuceLibraryCode/include_juce_video.o

# target to build an object file
JuceLibraryCode/include_juce_video.cpp.o:
	$(MAKE) -f CMakeFiles/FOO-0.1.out.dir/build.make CMakeFiles/FOO-0.1.out.dir/JuceLibraryCode/include_juce_video.cpp.o
.PHONY : JuceLibraryCode/include_juce_video.cpp.o

JuceLibraryCode/include_juce_video.i: JuceLibraryCode/include_juce_video.cpp.i

.PHONY : JuceLibraryCode/include_juce_video.i

# target to preprocess a source file
JuceLibraryCode/include_juce_video.cpp.i:
	$(MAKE) -f CMakeFiles/FOO-0.1.out.dir/build.make CMakeFiles/FOO-0.1.out.dir/JuceLibraryCode/include_juce_video.cpp.i
.PHONY : JuceLibraryCode/include_juce_video.cpp.i

JuceLibraryCode/include_juce_video.s: JuceLibraryCode/include_juce_video.cpp.s

.PHONY : JuceLibraryCode/include_juce_video.s

# target to generate assembly for a file
JuceLibraryCode/include_juce_video.cpp.s:
	$(MAKE) -f CMakeFiles/FOO-0.1.out.dir/build.make CMakeFiles/FOO-0.1.out.dir/JuceLibraryCode/include_juce_video.cpp.s
.PHONY : JuceLibraryCode/include_juce_video.cpp.s

Source/Main.o: Source/Main.cpp.o

.PHONY : Source/Main.o

# target to build an object file
Source/Main.cpp.o:
	$(MAKE) -f CMakeFiles/FOO-0.1.out.dir/build.make CMakeFiles/FOO-0.1.out.dir/Source/Main.cpp.o
.PHONY : Source/Main.cpp.o

Source/Main.i: Source/Main.cpp.i

.PHONY : Source/Main.i

# target to preprocess a source file
Source/Main.cpp.i:
	$(MAKE) -f CMakeFiles/FOO-0.1.out.dir/build.make CMakeFiles/FOO-0.1.out.dir/Source/Main.cpp.i
.PHONY : Source/Main.cpp.i

Source/Main.s: Source/Main.cpp.s

.PHONY : Source/Main.s

# target to generate assembly for a file
Source/Main.cpp.s:
	$(MAKE) -f CMakeFiles/FOO-0.1.out.dir/build.make CMakeFiles/FOO-0.1.out.dir/Source/Main.cpp.s
.PHONY : Source/Main.cpp.s

Source/MainComponent.o: Source/MainComponent.cpp.o

.PHONY : Source/MainComponent.o

# target to build an object file
Source/MainComponent.cpp.o:
	$(MAKE) -f CMakeFiles/FOO-0.1.out.dir/build.make CMakeFiles/FOO-0.1.out.dir/Source/MainComponent.cpp.o
.PHONY : Source/MainComponent.cpp.o

Source/MainComponent.i: Source/MainComponent.cpp.i

.PHONY : Source/MainComponent.i

# target to preprocess a source file
Source/MainComponent.cpp.i:
	$(MAKE) -f CMakeFiles/FOO-0.1.out.dir/build.make CMakeFiles/FOO-0.1.out.dir/Source/MainComponent.cpp.i
.PHONY : Source/MainComponent.cpp.i

Source/MainComponent.s: Source/MainComponent.cpp.s

.PHONY : Source/MainComponent.s

# target to generate assembly for a file
Source/MainComponent.cpp.s:
	$(MAKE) -f CMakeFiles/FOO-0.1.out.dir/build.make CMakeFiles/FOO-0.1.out.dir/Source/MainComponent.cpp.s
.PHONY : Source/MainComponent.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... FOO-0.1.out"
	@echo "... JuceLibraryCode/include_juce_audio_basics.o"
	@echo "... JuceLibraryCode/include_juce_audio_basics.i"
	@echo "... JuceLibraryCode/include_juce_audio_basics.s"
	@echo "... JuceLibraryCode/include_juce_audio_devices.o"
	@echo "... JuceLibraryCode/include_juce_audio_devices.i"
	@echo "... JuceLibraryCode/include_juce_audio_devices.s"
	@echo "... JuceLibraryCode/include_juce_audio_formats.o"
	@echo "... JuceLibraryCode/include_juce_audio_formats.i"
	@echo "... JuceLibraryCode/include_juce_audio_formats.s"
	@echo "... JuceLibraryCode/include_juce_audio_processors.o"
	@echo "... JuceLibraryCode/include_juce_audio_processors.i"
	@echo "... JuceLibraryCode/include_juce_audio_processors.s"
	@echo "... JuceLibraryCode/include_juce_core.o"
	@echo "... JuceLibraryCode/include_juce_core.i"
	@echo "... JuceLibraryCode/include_juce_core.s"
	@echo "... JuceLibraryCode/include_juce_cryptography.o"
	@echo "... JuceLibraryCode/include_juce_cryptography.i"
	@echo "... JuceLibraryCode/include_juce_cryptography.s"
	@echo "... JuceLibraryCode/include_juce_data_structures.o"
	@echo "... JuceLibraryCode/include_juce_data_structures.i"
	@echo "... JuceLibraryCode/include_juce_data_structures.s"
	@echo "... JuceLibraryCode/include_juce_events.o"
	@echo "... JuceLibraryCode/include_juce_events.i"
	@echo "... JuceLibraryCode/include_juce_events.s"
	@echo "... JuceLibraryCode/include_juce_graphics.o"
	@echo "... JuceLibraryCode/include_juce_graphics.i"
	@echo "... JuceLibraryCode/include_juce_graphics.s"
	@echo "... JuceLibraryCode/include_juce_gui_basics.o"
	@echo "... JuceLibraryCode/include_juce_gui_basics.i"
	@echo "... JuceLibraryCode/include_juce_gui_basics.s"
	@echo "... JuceLibraryCode/include_juce_gui_extra.o"
	@echo "... JuceLibraryCode/include_juce_gui_extra.i"
	@echo "... JuceLibraryCode/include_juce_gui_extra.s"
	@echo "... JuceLibraryCode/include_juce_opengl.o"
	@echo "... JuceLibraryCode/include_juce_opengl.i"
	@echo "... JuceLibraryCode/include_juce_opengl.s"
	@echo "... JuceLibraryCode/include_juce_video.o"
	@echo "... JuceLibraryCode/include_juce_video.i"
	@echo "... JuceLibraryCode/include_juce_video.s"
	@echo "... Source/Main.o"
	@echo "... Source/Main.i"
	@echo "... Source/Main.s"
	@echo "... Source/MainComponent.o"
	@echo "... Source/MainComponent.i"
	@echo "... Source/MainComponent.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

